### ISSUE TITLE
TODO: Test displacement map on aarch64.

### ISSUE THREAD

**Issue by syoyo** [lighttransport/embree-aarch64#5]
Test displacement map on aarch64

**Comment by syoyo** [comment]
Created `disp-debug` branch. And sometimes I get a segmentation failure.

```
==2959==ERROR: AddressSanitizer: SEGV on unknown address 0x000082fddeec (pc 0xffff96686828 bp 0xffffd64dc450 sp 0xffffd64baa10 T0)
==2959==The signal is caused by a READ memory access.
    #0 0xffff96686824 in embree::sse2::SubdivPatch1Intersector1::processLazyNode(embree::sse2::SubdivPatch1Precalculations<embree::sse2::GridSOAIntersector1::Precalculations>&, embree::IntersectContext*, embree::sse2::GridSOA const*, unsigned long&) /home/ubuntu/work/embree-aarch64/kernels/bvh/../geometry/subdivpatch1_intersector.h:53:21
    #1 0xffff96686824 in void embree::sse2::SubdivPatch1Intersector1::intersect<4, 4, true>(embree::Accel::Intersectors const*, embree::sse2::SubdivPatch1Precalculations<embree::sse2::GridSOAIntersector1::Precalculations>&, embree::RayHitK<1>&, embree::IntersectContext*, embree::sse2::GridSOA const*, unsigned long, embree::sse2::TravRay<4, 4, true> const&, unsigned long&) /home/ubuntu/work/embree-aarch64/kernels/bvh/../geometry/subdivpatch1_intersector.h:63
    #2 0xffff96686824 in embree::sse2::BVHNIntersector1<4, 1, true, embree::sse2::SubdivPatch1Intersector1>::intersect(embree::Accel::Intersectors const*, embree::RayHitK<1>&, embree::IntersectContext*) /home/ubuntu/work/embree-aarch64/kernels/bvh/bvh_intersector1.cpp:114
    #3 0xffff94d396a8 in embree::Accel::Intersectors::intersect(RTCRayHit&, embree::IntersectContext*) /home/ubuntu/work/embree-aarch64/kernels/common/accel.h:277:9
    #4 0xffff94d396a8 in rtcIntersect1 /home/ubuntu/work/embree-aarch64/kernels/common/rtcore.cpp:312
    #5 0x502314 in main /home/ubuntu/work/embree-aarch64/test/disp/main.cc:437:9
    #6 0xffff948ff89c in __libc_start_main /build/glibc-BinVK7/glibc-2.23/csu/libc-start.c:291

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/ubuntu/work/embree-aarch64/kernels/bvh/../geometry/subdivpatch1_intersector.h:53:21 in embree::sse2::SubdivPatch1Intersector1::processLazyNode(embree::sse2::SubdivPatch1Precalculations<embree::sse2::GridSOAIntersector1::Precalculations>&, embree::IntersectContext*, embree::sse2::GridSOA const*, unsigned long&)
==2959==ABORTING
```

**Comment by syoyo** [comment]
Apparently this commit fixes the bug > https://github.com/lighttransport/embree-aarch64/commit/befebec6f797d33589991684ba8e5ea05c222e70
